name: Publish docker images

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push docker images to GitHub Packages
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/scout-ch/scoutti
      IMAGE_NAME: scoutti

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=true
            type=ref,event=tag,enable=${{ github.event.ref_type == 'tag' }}
          flavor: |
            latest=false
      - name: Build docker
        id: build-docker
        uses: docker/build-push-action@v3
        with:
          target: scoutti-deploy
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Push docker
        uses: docker/build-push-action@v3
        with:
          push: true
          target: scout-ch/scoutti
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: worker@levell.ch
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          pull_images_first: true
          deploy_path: /home/worker/levell/scoutti
          stack_file_name: docker-compose.prod.yml
          args: --with-registry-auth --prune scoutti
